<script setup lang="ts">
import { ref } from 'vue'
import { cn } from '@/lib/cn'
import { fmtClock } from '@/lib/format'
import { PEOPLE } from '@/data/people'
import { SUMMARY } from '@/data/summary'
import Icon from '@/components/Icon.vue'
import Avatar from '@/components/Avatar.vue'
import SectionTitle from './SectionTitle.vue'

const emit = defineEmits<{ seek: [t: number] }>()

const PROMPT_PRESETS: Record<string, string> = {
  Default:
    'Summarize this meeting into a concise TL;DR, key points, decisions, and action items with owners. Be specific and never invent details.',
  Brief:
    'Give a 2–3 sentence overview and a short bullet list of action items only.',
  'Action items':
    'Extract only the action items, each with an owner and a due date. Ignore everything else.',
  'Decisions & risks':
    'Focus on decisions made and any risks, blockers or open questions raised. List owners for each follow-up.',
}

const done = ref<boolean[]>([false, false, false])
const prompt = ref(PROMPT_PRESETS['Default'])
const preset = ref('Default')
const promptOpen = ref(false)
const regenerating = ref(false)

function pickPreset(p: string) {
  preset.value = p
  prompt.value = PROMPT_PRESETS[p]
}
function regen() {
  promptOpen.value = false
  regenerating.value = true
  setTimeout(() => (regenerating.value = false), 1500)
}
function toggleDone(i: number) {
  done.value = done.value.map((v, j) => (j === i ? !v : v))
}
function onPromptInput(v: string) {
  prompt.value = v
  preset.value = 'Custom'
}
</script>

<template>
  <div class="relative">
    <div
      v-if="regenerating"
      class="absolute inset-0 z-20 flex items-start justify-center pt-20"
    >
      <div
        class="flex items-center gap-2.5 text-[13.5px] font-medium px-4 py-2.5 rounded-xl bg-base-100 shadow-lg border border-base-content/10"
      >
        <span
          class="loading loading-spinner loading-sm"
          :style="{ color: 'var(--accent)' }"
        />
        Regenerating summary…
      </div>
    </div>
    <div
      :class="
        cn(
          'grid grid-cols-1 xl:grid-cols-[1fr_300px] gap-7 transition-opacity',
          regenerating && 'opacity-40 pointer-events-none',
        )
      "
    >
      <div class="min-w-0 space-y-7">
        <!-- AI pill -->
        <div class="flex items-center justify-between gap-3 flex-wrap">
          <div
            class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-[12.5px] font-semibold whitespace-nowrap"
            :style="{
              background: 'color-mix(in oklab, var(--accent) 12%, transparent)',
              color: 'var(--accent)',
            }"
          >
            <Icon name="sparkles" :size="15" /> Generated by meetbud AI
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-base-content/40 hidden sm:inline"
              >claude-sonnet · 2 min ago</span
            >
            <button
              class="btn btn-ghost btn-xs gap-1 text-base-content/60"
              @click="promptOpen = true"
            >
              <Icon name="edit" :size="13" /> Customize prompt
            </button>
            <button
              class="btn btn-ghost btn-xs gap-1 text-base-content/60"
              @click="regen"
            >
              <Icon name="refresh" :size="13" /> Regenerate
            </button>
          </div>
        </div>

        <!-- TL;DR -->
        <div class="rounded-2xl border border-base-content/10 bg-base-100 p-5">
          <SectionTitle icon="flag">TL;DR</SectionTitle>
          <p class="text-[14.5px] leading-relaxed text-base-content/75">
            {{ SUMMARY.tldr }}
          </p>
        </div>

        <!-- Key points -->
        <div>
          <SectionTitle icon="list-checks">Key points</SectionTitle>
          <ul class="space-y-2.5">
            <li
              v-for="(k, i) in SUMMARY.keyPoints"
              :key="i"
              class="flex gap-3 text-[14px] leading-relaxed text-base-content/75"
            >
              <span
                class="mt-2 w-1.5 h-1.5 rounded-full shrink-0"
                :style="{ background: 'var(--accent)' }"
              />
              {{ k }}
            </li>
          </ul>
        </div>

        <!-- Action items -->
        <div>
          <SectionTitle icon="check-circle">Action items</SectionTitle>
          <div class="space-y-2.5">
            <div
              v-for="(a, i) in SUMMARY.actionItems"
              :key="i"
              :class="
                cn(
                  'flex items-start gap-3 rounded-xl border border-base-content/10 bg-base-100 p-3.5 transition-opacity',
                  done[i] && 'opacity-55',
                )
              "
            >
              <input
                type="checkbox"
                class="checkbox checkbox-sm mt-0.5"
                :checked="done[i]"
                :style="
                  done[i]
                    ? {
                        backgroundColor: 'var(--accent)',
                        borderColor: 'var(--accent)',
                      }
                    : {}
                "
                @change="toggleDone(i)"
              />
              <div class="min-w-0 flex-1">
                <p
                  :class="
                    cn(
                      'text-[14px] leading-snug text-base-content/80',
                      done[i] && 'line-through',
                    )
                  "
                >
                  {{ a.text }}
                </p>
                <div class="flex items-center gap-2 mt-2">
                  <Avatar :person="PEOPLE[a.who]" :size="20" />
                  <span class="text-[12px] font-medium text-base-content/60">{{
                    PEOPLE[a.who].name
                  }}</span>
                  <span class="badge badge-sm badge-ghost gap-1"
                    ><Icon name="clock" :size="11" />{{ a.due }}</span
                  >
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Decisions -->
        <div>
          <SectionTitle icon="flag">Decisions</SectionTitle>
          <ul class="space-y-2.5">
            <li
              v-for="(d, i) in SUMMARY.decisions"
              :key="i"
              class="flex gap-3 text-[14px] leading-relaxed text-base-content/75 rounded-xl bg-base-200/50 p-3.5"
            >
              <Icon
                name="check"
                :size="17"
                class="mt-0.5 shrink-0"
                :style="{ color: 'var(--accent)' }"
              />{{ d }}
            </li>
          </ul>
        </div>
      </div>

      <!-- right rail -->
      <div class="space-y-5">
        <div
          class="rounded-2xl border border-base-content/10 bg-base-100 p-4 xl:sticky xl:top-0"
        >
          <h4
            class="text-[11.5px] font-bold uppercase tracking-wide text-base-content/45 mb-3"
          >
            Chapters
          </h4>
          <ul class="space-y-1">
            <li v-for="(tp, i) in SUMMARY.topics" :key="i">
              <button
                class="w-full flex items-center gap-2.5 px-2 py-1.5 rounded-lg hover:bg-base-content/5 text-left group"
                @click="emit('seek', tp.t)"
              >
                <span
                  class="font-mono text-[11.5px] text-base-content/40 group-hover:text-[color:var(--accent)] tabular-nums"
                  >{{ fmtClock(tp.t) }}</span
                >
                <span
                  class="text-[13px] font-medium text-base-content/70 group-hover:text-base-content leading-snug"
                  >{{ tp.label }}</span
                >
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div
      v-if="promptOpen"
      class="fixed inset-0 z-[80] flex items-center justify-center p-4"
      @click="promptOpen = false"
    >
      <div class="absolute inset-0 bg-black/40" />
      <div
        class="relative bg-base-100 rounded-2xl shadow-2xl border border-base-content/10 w-full max-w-lg p-6 tab-anim"
        @click.stop
      >
        <div class="flex items-start justify-between">
          <div class="flex items-center gap-2.5">
            <div
              class="w-9 h-9 rounded-lg flex items-center justify-center"
              :style="{
                background:
                  'color-mix(in oklab, var(--accent) 13%, transparent)',
                color: 'var(--accent)',
              }"
            >
              <Icon name="sparkles" :size="18" />
            </div>
            <div>
              <h2 class="text-base font-extrabold tracking-tight">
                Customize summary
              </h2>
              <p class="text-[12.5px] text-base-content/50">
                Tell meetbud how to summarize this meeting.
              </p>
            </div>
          </div>
          <button
            class="btn btn-ghost btn-sm btn-square"
            @click="promptOpen = false"
          >
            <Icon name="x" :size="18" />
          </button>
        </div>
        <div class="flex flex-wrap gap-2 mt-4">
          <button
            v-for="p in Object.keys(PROMPT_PRESETS)"
            :key="p"
            :class="
              cn(
                'px-3 h-8 rounded-lg text-[12.5px] font-medium border transition-colors',
                preset === p
                  ? 'text-white border-transparent'
                  : 'border-base-content/12 text-base-content/65 hover:bg-base-content/5',
              )
            "
            :style="preset === p ? { background: 'var(--accent)' } : undefined"
            @click="pickPreset(p)"
          >
            {{ p }}
          </button>
        </div>
        <textarea
          :value="prompt"
          rows="5"
          class="w-full mt-3 p-3.5 rounded-xl bg-base-200/60 border border-base-content/10 text-[13.5px] leading-relaxed outline-none focus:border-[color:var(--accent)] focus:bg-base-100 transition-colors resize-none"
          @input="onPromptInput(($event.target as HTMLTextAreaElement).value)"
        />
        <div class="flex items-center justify-end gap-2 mt-4">
          <button class="btn btn-ghost btn-sm" @click="promptOpen = false">
            Cancel
          </button>
          <button
            class="btn btn-sm text-white border-0"
            :style="{ background: 'var(--accent)' }"
            @click="regen"
          >
            <Icon name="sparkles" :size="15" /> Regenerate summary
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
